### ISSUE TITLE
No function is detected in runtime

### ISSUE THREAD

**Issue by mortezasoft** [anthonychu/functions-puppeteer-sharp-razor#1]
I downloaded the source code and ran it on my Mac. As shown in the following image, it does not detect any functions! Am I missing something?

<img width="1036" alt="Bildschirmfoto 2020-10-15 um 13 47 01" src="https://user-images.githubusercontent.com/876408/96119638-9254c880-0eed-11eb-8010-46e6dd16673a.png">

**Comment by anthonychu** [comment]
How did you start it? Can you show more of the console output? If you run `func start --verbose` you should get more details. The command should run a build and start the app. Perhaps it’s missing local.settings.json. If you run `func init` it should generate one for you.

**Comment by mortezasoft** [comment]
Thanks! Missing `local.settings.json` was the cause. I forgot about `FUNCTIONS_WORKER_RUNTIME` and thought since it's just an HTTP triggered function, we do not need it.
